apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: holy-namespace
  labels:
    app: Orders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Orders
  template:
    metadata:
      labels:
        app: Orders
    spec:
      containers:
      - name: orders-container
        image: registry.gitlab.au.dk/swwao/demo-projs/typescript-mongodb-crud  # Update with your GitLab image URL
        ports:
        - containerPort: 80
        env:
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-db-secret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-db-secret
                key: MONGO_INITDB_ROOT_PASSWORD
          - name: MONGODB_DBNAME
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: MONGODB_DBNAME
          - name: MONGODB_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: MONGODB_HOSTNAME
          - name: REL_URL_PATH
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: REL_URL_PATH
      imagePullSecrets:
        - name: registry-credentials  # Ensure this matches your Docker registry secret
