apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: holy-namespace
spec:
  clusterIP: None
  selector:
    role: mongo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 27017
