apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: holy-namespace
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
