apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: holy-namespace
spec:
  serviceName: "mongo-service"
  replicas: 3
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-volume-pvc
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume-pvc
        namespace: holy-namespace
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
