apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume-pv
spec:
  storageClassName: "local-path"
  capacity:
    storage: 5Gi
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: holy-namespace
    name: mongo-volume-pvc
  hostPath:
    path: "~/slet/"
