apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secret
  namespace: holy-namespace
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==  # base64 encoded 'root'
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==  # base64 encoded 'example'
  